# Generated by Django 2.2.4 on 2019-08-13 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_type', models.CharField(max_length=20)),
                ('book_authors', models.CharField(max_length=50)),
                ('book_publisher', models.CharField(max_length=50)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('book_add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('book_status', models.IntegerField(max_length=1)),
            ],
            options={
                'db_table': 'tb_books',
            },
        ),
        migrations.CreateModel(
            name='Borrows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('borrow_time', models.DateTimeField(default=datetime.datetime.now)),
                ('borrow_status', models.IntegerField(max_length=1)),
                ('return_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('user_mobile', models.IntegerField(max_length=11)),
                ('user_password', models.CharField(max_length=32)),
                ('user_sex', models.IntegerField(default=1)),
                ('user_state', models.IntegerField(default=1)),
                ('user_add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'tb_users',
            },
        ),
    ]
