# Generated by Django 2.2.4 on 2019-08-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMS', '0002_auto_20190813_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='borrows',
            name='book_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='borrows',
            name='borrow_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='borrows',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='user_mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='user_sex',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='user_state',
            field=models.IntegerField(),
        ),
    ]
