# Generated by Django 2.2.4 on 2019-08-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMS', '0003_auto_20190813_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='user_mobile',
            field=models.BigIntegerField(),
        ),
    ]
