# Generated by Django 2.2.4 on 2019-08-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMS', '0005_auto_20190814_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrows',
            name='return_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
