# Generated by Django 2.2.4 on 2019-08-14 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookMS', '0007_auto_20190814_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrows',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookMS.Books'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_sex',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_state',
            field=models.IntegerField(default=0),
        ),
    ]
