# Generated by Django 2.2.4 on 2019-08-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookMS', '0008_auto_20190814_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrows',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookMS.Users'),
        ),
    ]
