# Generated by Django 2.2.4 on 2019-08-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMS', '0009_auto_20190814_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_sn',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_mobile',
            field=models.BigIntegerField(default=0),
        ),
    ]
