# Generated by Django 2.2.4 on 2019-08-16 16:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookMS', '0011_auto_20190815_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': '图书管理', 'verbose_name_plural': '图书管理'},
        ),
        migrations.AlterModelOptions(
            name='borrows',
            options={'verbose_name': '借阅管理', 'verbose_name_plural': '借阅管理'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterField(
            model_name='books',
            name='book_add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_authors',
            field=models.CharField(max_length=50, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_name',
            field=models.CharField(max_length=50, verbose_name='图书名称'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_publisher',
            field=models.CharField(max_length=50, verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_status',
            field=models.IntegerField(choices=[(0, '启用'), (1, '禁用')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_type',
            field=models.CharField(max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='borrows',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookMS.Books', verbose_name='图书编号'),
        ),
        migrations.AlterField(
            model_name='borrows',
            name='borrow_status',
            field=models.IntegerField(choices=[(0, '借阅中'), (1, '已归还')], default=0, verbose_name='借阅状态'),
        ),
        migrations.AlterField(
            model_name='borrows',
            name='borrow_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='借阅时间'),
        ),
        migrations.AlterField(
            model_name='borrows',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='应还时间'),
        ),
        migrations.AlterField(
            model_name='borrows',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookMS.Users', verbose_name='用户编号'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_mobile',
            field=models.BigIntegerField(default=0, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_sex',
            field=models.IntegerField(choices=[(1, '男'), (0, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_sn',
            field=models.BigIntegerField(verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_state',
            field=models.IntegerField(choices=[(0, '启用'), (1, '禁用')], default=0, verbose_name='状态'),
        ),
    ]
